# constants.py
REG_FIFO                = 0x00
REG_OP_MODE             = 0x01
REG_FRF_MSB             = 0x06
REG_FRF_MID             = 0x07
REG_FRF_LSB             = 0x08
REG_PA_CONFIG           = 0x09
REG_FIFO_ADDR_PTR       = 0x0D
REG_FIFO_TX_BASE_ADDR   = 0x0E
REG_FIFO_RX_BASE_ADDR   = 0x0F
REG_FIFO_RX_CURRENT_ADDR= 0x10
REG_IRQ_FLAGS           = 0x12
REG_RX_NB_BYTES         = 0x13
REG_PKT_RSSI_VALUE      = 0x1A
REG_MODEM_CONFIG1       = 0x1D
REG_MODEM_CONFIG2       = 0x1E
REG_PAYLOAD_LENGTH      = 0x22
REG_MODEM_CONFIG3       = 0x26

IRQ_RX_DONE_MASK = 0x40

MODE_SLEEP   = 0x80
MODE_STDBY   = 0x81
MODE_TX      = 0x83
MODE_RXCONT  = 0x85